package net.ttrstudios.in2000_team_47_app.backend.utils

import net.ttrstudios.in2000_team_47_app.R

fun selectWeatherIcon(symbolCode: String?): Int {
    return when (symbolCode) {
        "clearsky_day" -> R.drawable.met_clearsky_day
        "clearsky_night" -> R.drawable.met_clearsky_night
        "clearsky_polartwilight" -> R.drawable.met_clearsky_polartwilight
        "cloudy" -> R.drawable.met_cloudy
        "fair_day" -> R.drawable.met_fair_day
        "fair_night" -> R.drawable.met_fair_night
        "fair_polartwilight" -> R.drawable.met_fair_polartwilight
        "fog" -> R.drawable.met_fog
        "heavyrain" -> R.drawable.met_heavyrain
        "heavyrainandthunder" -> R.drawable.met_heavyrainandthunder
        "heavyrainshowers_day" -> R.drawable.met_heavyrainshowers_day
        "heavyrainshowers_night" -> R.drawable.met_heavyrainshowers_night
        "heavyrainshowers_polartwilight" -> R.drawable.met_heavyrainshowers_polartwilight
        "heavyrainshowersandthunder_day" -> R.drawable.met_heavyrainshowersandthunder_day
        "heavyrainshowersandthunder_night" -> R.drawable.met_heavyrainshowersandthunder_night
        "heavyrainshowersandthunder_polartwilight" -> R.drawable.met_heavyrainshowersandthunder_polartwilight
        "heavysleet" -> R.drawable.met_heavysleet
        "heavysleetandthunder" -> R.drawable.met_heavysleetandthunder
        "heavysleetshowers_day" -> R.drawable.met_heavysleetshowers_day
        "heavysleetshowers_night" -> R.drawable.met_heavysleetshowers_night
        "heavysleetshowers_polartwilight" -> R.drawable.met_heavysleetshowers_polartwilight
        "heavysleetshowersandthunder_day" -> R.drawable.met_heavysleetshowersandthunder_day
        "heavysleetshowersandthunder_night" -> R.drawable.met_heavysleetshowersandthunder_night
        "heavysleetshowersandthunder_polartwilight" -> R.drawable.met_heavysleetshowersandthunder_polartwilight
        "heavysnow" -> R.drawable.met_heavysnow
        "heavysnowandthunder" -> R.drawable.met_heavysnowandthunder
        "heavysnowshowers_day" -> R.drawable.met_heavysnowshowers_day
        "heavysnowshowers_night" -> R.drawable.met_heavysnowshowers_night
        "heavysnowshowers_polartwilight" -> R.drawable.met_heavysnowshowers_polartwilight
        "heavysnowshowersandthunder_day" -> R.drawable.met_heavysnowshowersandthunder_day
        "heavysnowshowersandthunder_night" -> R.drawable.met_heavysnowshowersandthunder_night
        "heavysnowshowersandthunder_polartwilight" -> R.drawable.met_heavysnowshowersandthunder_polartwilight
        "lightrain" -> R.drawable.met_lightrain
        "lightrainandthunder" -> R.drawable.met_lightrainandthunder
        "lightrainshowers_day" -> R.drawable.met_lightrainshowers_day
        "lightrainshowers_night" -> R.drawable.met_lightrainshowers_night
        "lightrainshowers_polartwilight" -> R.drawable.met_lightrainshowers_polartwilight
        "lightrainshowersandthunder_day" -> R.drawable.met_lightrainshowersandthunder_day
        "lightrainshowersandthunder_night" -> R.drawable.met_lightrainshowersandthunder_night
        "lightrainshowersandthunder_polartwilight" -> R.drawable.met_lightrainshowersandthunder_polartwilight
        "lightsleet" -> R.drawable.met_lightsleet
        "lightsleetandthunder" -> R.drawable.met_lightsleetandthunder
        "lightsleetshowers_day" -> R.drawable.met_lightsleetshowers_day
        "lightsleetshowers_night" -> R.drawable.met_lightsleetshowers_night
        "lightsleetshowers_polartwilight" -> R.drawable.met_lightsleetshowers_polartwilight
        "lightsnow" -> R.drawable.met_lightsnow
        "lightsnowandthunder" -> R.drawable.met_lightsnowandthunder
        "lightsnowshowers_day" -> R.drawable.met_lightsnowshowers_day
        "lightsnowshowers_night" -> R.drawable.met_lightsnowshowers_night
        "lightsnowshowers_polartwilight" -> R.drawable.met_lightsnowshowers_polartwilight
        "lightssleetshowersandthunder_day" -> R.drawable.met_lightssleetshowersandthunder_day
        "lightssleetshowersandthunder_night" -> R.drawable.met_lightssleetshowersandthunder_night
        "lightssleetshowersandthunder_polartwilight" -> R.drawable.met_lightssleetshowersandthunder_polartwilight
        "lightssnowshowersandthunder_day" -> R.drawable.met_lightssnowshowersandthunder_day
        "lightssnowshowersandthunder_night" -> R.drawable.met_lightssnowshowersandthunder_night
        "lightssnowshowersandthunder_polartwilight" -> R.drawable.met_lightssnowshowersandthunder_polartwilight
        "partlycloudy_day" -> R.drawable.met_partlycloudy_day
        "partlycloudy_night" -> R.drawable.met_partlycloudy_night
        "partlycloudy_polartwilight" -> R.drawable.met_partlycloudy_polartwilight
        "rain" -> R.drawable.met_rain
        "rainandthunder" -> R.drawable.met_rainandthunder
        "rainshowers_day" -> R.drawable.met_rainshowers_day
        "rainshowers_night" -> R.drawable.met_rainshowers_night
        "rainshowers_polartwilight" -> R.drawable.met_rainshowers_polartwilight
        "rainshowersandthunder_day" -> R.drawable.met_rainshowersandthunder_day
        "rainshowersandthunder_night" -> R.drawable.met_rainshowersandthunder_night
        "rainshowersandthunder_polartwilight" -> R.drawable.met_rainshowersandthunder_polartwilight
        "sleet" -> R.drawable.met_sleet
        "sleetandthunder" -> R.drawable.met_sleetandthunder
        "sleetshowers_day" -> R.drawable.met_sleetshowers_day
        "sleetshowers_night" -> R.drawable.met_sleetshowers_night
        "sleetshowers_polartwilight" -> R.drawable.met_sleetshowers_polartwilight
        "sleetshowersandthunder_day" -> R.drawable.met_sleetshowersandthunder_day
        "sleetshowersandthunder_night" -> R.drawable.met_sleetshowersandthunder_night
        "sleetshowersandthunder_polartwilight" -> R.drawable.met_sleetshowersandthunder_polartwilight
        "snow" -> R.drawable.met_snow
        "snowandthunder" -> R.drawable.met_snowandthunder
        "snowshowers_day" -> R.drawable.met_snowshowers_day
        "snowshowers_night" -> R.drawable.met_snowshowers_night
        "snowshowers_polartwilight" -> R.drawable.met_snowshowers_polartwilight
        "snowshowersandthunder_day" -> R.drawable.met_snowshowersandthunder_day
        "snowshowersandthunder_night" -> R.drawable.met_snowshowersandthunder_night
        "snowshowersandthunder_polartwilight" -> R.drawable.met_snowshowersandthunder_polartwilight
        else -> R.drawable.met_fair_day
    }
}